### ISSUE TITLE
I encountered a problem while running the GUI_test.py, It seems that there doesn't exist an file named app_details.csv

### ISSUE THREAD

**Issue by zhengwjie** [GUIDesignResearch/GUIGAN#5]
Traceback (most recent call last):
  File "/home/zhengwanjie/GAN_models/GUIGAN/code/GUIGAN_test.py", line 79, in <module>
    appsl, appsd = get_s_app(file_csv, st_dir)
  File "/home/zhengwanjie/GAN_models/GUIGAN/code/./StyleEmbedding/load_data.py", line 93, in get_s_app
    cv_file = csv.reader(open(file_csv,'r', encoding='UTF-8'))
FileNotFoundError: [Errno 2] No such file or directory: 'app_details.csv'

**Comment by Kostich31** [comment]
Do you find a solution of that?

**Comment by TigerGod** [comment]
me too.
